version: "3.8"

services:
  app:
    image: #{DOCKER_DEPLOY_APP_IMAGE}#
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "3000:3000"

  crons:
    image: #{DOCKER_DEPLOY_CRONS_IMAGE}#
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - "5432:5432"

  redis:
    restart: unless-stopped
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  redis-data:
